#ALLO ????

version: '3.7'

services:
    moneymakers:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: production

networks:
    default:
        name: nginx_default
        driver: bridge
