#ALLO ????

version: '3.7'

services:
    moneymakers:
        container_name: moneymakers
        build: .
        environment:
            NODE_ENV: production

networks:
    default:
        name: nginx_default
        driver: bridge
