name: Nuxt CI

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install dependencies
              run: yarn install

            - name: Build the application
              run: yarn build

            - name: Run tests
              run: yarn test