name: Nuxt CI

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: self-hosted

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '18'

            -   name: Cache Yarn dependencies
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.yarn/cache
                        node_modules
                    key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-yarn-

            -   name: Build the Docker image
                run: sudo docker compose build --build-arg ENV=prod

            -   name: Create and start container
                run: sudo docker compose up -d

            -   name: Display container logs
                run: sudo docker logs $(sudo docker ps -q -f name=moneymakers)